import {useMemo,useRef,useState} from 'react';
import type {Project,Row} from '../types';
import {pdfOut,safe} from '../exports/files';
import {formatPercent} from '../utils/format';

function monthName(key:string){return new Date(`${key}-01T12:00:00`).toLocaleDateString('id-ID',{month:'long',year:'numeric'})}
function summary(rows:Row[]){return rows.reduce((a,r)=>({planned:a.planned+(Number(r.plannedWeekly)||0),actual:a.actual+(Number(r.actualWeekly)||0),weeks:a.weeks+1}),{planned:0,actual:0,weeks:0})}
function deviation(x:{planned:number;actual:number}){return Math.min(100,x.actual)-Math.min(100,x.planned)}
export default function MonthlyRecap({project,progress}:{project:Project;progress:Row[]}){
 const today=new Date(),[month,setMonth]=useState(`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`),report=useRef<HTMLDivElement>(null);
 const previous=useMemo(()=>{const d=new Date(`${month}-01T12:00:00`);d.setMonth(d.getMonth()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`},[month]);
 const prior=summary(progress.filter(r=>String(r.date||'').slice(0,7)===previous));
 const current=summary(progress.filter(r=>String(r.date||'').slice(0,7)===month));
 const totalPrevious=summary(progress.filter(r=>String(r.date||'').slice(0,7)<=previous));
 const cumulative=summary(progress.filter(r=>String(r.date||'').slice(0,7)<=month));
 const periods=[{name:'Bulan lalu',label:monthName(previous),...prior,total:totalPrevious},{name:'Bulan ini',label:monthName(month),...current,total:cumulative},{name:'Kumulatif sampai saat ini',label:`s.d. ${monthName(month)}`,...cumulative,total:cumulative}];
 return <><div className="pagehead"><div><h1>Rekap Bulanan</h1><p>Ringkasan progres rencana, aktual, dan deviasi per bulan proyek.</p></div><div className="head-actions"><label className="month-picker">Pilih bulan<input type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/></label><button className="primary" onClick={()=>report.current&&void pdfOut(report.current,`${safe(project.name)}_Rekap_Bulanan_${month}.pdf`,'REKAP PROGRES BULANAN',project)}>Download PDF</button></div></div>
 <div className="panel monthly-report" ref={report}><div className="monthly-heading">{project.logo&&<img src={project.logo} alt="Logo perusahaan"/>}<div><small>PROJECT PROGRESS REPORT · {project.number||'PROJECT'}</small><h2>Rekap Progres Bulanan</h2><p>{project.name} · {monthName(month)}</p></div></div><div className="monthly-grid">{periods.map(x=><section className={`monthly-card ${x.name==='Bulan ini'?'current-month':''}`} key={x.name}><small>{x.name}</small><h3>{x.label}</h3><div><span>Rencana</span><b>{formatPercent(Math.min(100,x.planned))}</b></div><div><span>Aktual</span><b>{formatPercent(Math.min(100,x.actual))}</b></div><div><span>Deviasi</span><b className={deviation(x)<0?'negative':''}>{formatPercent(deviation(x))}</b></div><div className="month-period-total"><span>Total kumulatif s.d. periode</span><strong>Rencana {formatPercent(Math.min(100,x.total.planned))} · Aktual {formatPercent(Math.min(100,x.total.actual))} · Deviasi {formatPercent(deviation(x.total))}</strong></div>{x.weeks===0&&<p className="no-month-data">Belum ada progres yang dicatat untuk {x.label}.</p>}<footer>{x.weeks} minggu dilaporkan</footer></section>)}</div><h3 className="monthly-table-title">Ringkasan periode</h3><div className="table-scroll"><table><thead><tr><th>Periode</th><th>Rencana</th><th>Aktual</th><th>Deviasi</th><th>Jumlah minggu</th></tr></thead><tbody>{periods.map(x=><tr key={x.name}><td>{x.name} · {x.label}</td><td>{formatPercent(Math.min(100,x.planned))}</td><td>{formatPercent(Math.min(100,x.actual))}</td><td>{formatPercent(deviation(x))}</td><td>{x.weeks}</td></tr>)}</tbody></table></div><p className="monthly-note">Progres dihitung dari penjumlahan planned weekly dan actual weekly pada Weekly Progress untuk proyek ini. Kumulatif menjumlahkan data sejak awal pencatatan sampai bulan yang dipilih.</p><div className="approval monthly-approval"><div><b>PIHAK PERTAMA</b><p>{project.approval.firstCompany}</p>{project.approval.firstSignature&&<img src={project.approval.firstSignature} alt="Tanda tangan pihak pertama"/>}<p>{project.approval.firstName}<br/>{project.approval.firstPosition}</p></div><div><b>PIHAK KEDUA</b><p>{project.approval.secondCompany}</p>{project.approval.secondSignature&&<img src={project.approval.secondSignature} alt="Tanda tangan pihak kedua"/>}<p>{project.approval.secondName}<br/>{project.approval.secondPosition}</p></div></div></div></>
}
