import type {jsPDF} from 'jspdf';import type {Project,Row,Store} from '../types';
export const safe=(s:string)=>s.replace(/[^a-z0-9-_]+/gi,'_').replace(/^_+|_+$/g,'')||'project';
export function download(blob:Blob,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export function jsonOut(data:any,name:string){download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),name)}
export async function csvOut(rows:any[],name:string){const XLSX=await import('xlsx');const ws=XLSX.utils.json_to_sheet(rows);download(new Blob([XLSX.utils.sheet_to_csv(ws)],{type:'text/csv'}),name)}
export async function excelOut(rows:any[],name:string,sheet='Data'){const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),sheet.slice(0,31));XLSX.writeFile(wb,name)}
export async function templateOut(columns:string[],name:string){const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([Object.fromEntries(columns.map(column=>[column,'']))]),name.slice(0,31));XLSX.writeFile(wb,`${safe(name)}_template.xlsx`)}
export async function readSpreadsheet(buffer:ArrayBuffer){const XLSX=await import('xlsx');const workbook=XLSX.read(buffer,{type:'array',cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];return XLSX.utils.sheet_to_json(sheet)}
export async function projectWorkbook(p:Project,s:Store){const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();const add=(n:string,d:any[])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d),n);add('Project Information',[{...p,approval:undefined}]);for(const [name,key] of [['WBS','wbs'],['Weekly Progress','progress'],['Activities','activities'],['Issues','issues'],['Materials','materials']] as const)add(name,(s[key] as Row[]).filter(x=>x.projectId===p.id));const progress=(s.progress.filter(x=>x.projectId===p.id).sort((a,b)=>a.week-b.week));let pc=0,ac=0;add('S-Curve Data',progress.map(x=>{pc+=+x.plannedWeekly||0;ac+=+x.actualWeekly||0;return {Week:x.week,Date:x.date,'Planned Weekly':x.plannedWeekly,'Actual Weekly':x.actualWeekly,'Planned Cumulative':pc,'Actual Cumulative':ac,Deviation:ac-pc}}));const a=p.approval;add('Approval',[{Report:'Project approval',Project:p.name,Number:p.number,ReportDate:new Date().toLocaleDateString()},{Party:'PIHAK PERTAMA',Company:a.firstCompany,Name:a.firstName,Position:a.firstPosition},{Party:'PIHAK KEDUA',Company:a.secondCompany,Name:a.secondName,Position:a.secondPosition}]);XLSX.writeFile(wb,`${safe(p.name)}_Project.xlsx`)}
export async function elementPng(el:HTMLElement,name:string){const html2canvas=(await import('html2canvas')).default;const c=await html2canvas(el,{scale:2,backgroundColor:'#fff',useCORS:true});c.toBlob(b=>b&&download(b,name),'image/png')}
export function chartSvg(el:HTMLElement,name:string){const svg=el.querySelector('svg');if(!svg)throw Error('Chart is not rendered yet.');const copy=svg.cloneNode(true) as SVGSVGElement;copy.setAttribute('xmlns','http://www.w3.org/2000/svg');copy.setAttribute('width',String(svg.clientWidth||900));copy.setAttribute('height',String(svg.clientHeight||360));const blob=new Blob([new XMLSerializer().serializeToString(copy)],{type:'image/svg+xml'});download(blob,name)}
export async function pdfOut(el:HTMLElement,name:string,title:string,project?:Project){const [{jsPDF},{default:html2canvas}]=await Promise.all([import('jspdf'),import('html2canvas')]);const clone=el.cloneNode(true) as HTMLElement;clone.style.position='fixed';clone.style.left='-12000px';clone.style.top='0';clone.style.width=`${el.offsetWidth||900}px`;clone.style.background='#fff';clone.style.color='#000000';clone.style.fontFamily='"Times New Roman",Times,serif';clone.querySelectorAll<HTMLElement>('*').forEach(n=>{n.style.fontFamily='"Times New Roman",Times,serif';n.style.color='#000000'});clone.querySelectorAll<SVGElement>('svg text').forEach(n=>{n.style.fontFamily='"Times New Roman",Times,serif'});clone.querySelectorAll<HTMLElement>('.approval').forEach(n=>{n.style.display='none'});document.body.appendChild(clone);let canvas:HTMLCanvasElement;try{canvas=await html2canvas(clone,{scale:1.5,backgroundColor:'#fff',useCORS:true})}finally{clone.remove()}const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});const fullW=186,fullH=canvas.height*fullW/canvas.width,top=32;const totalPages=fullH<=175?1:Math.ceil((fullH-175)/250)+1;const sliceH=fullH/totalPages;for(let page=0;page<totalPages;page++){if(page)pdf.addPage();drawReportHeader(pdf,title,project,page+1,totalPages);pdf.addImage(canvas.toDataURL('image/png'),'PNG',12,top-page*sliceH,fullW,fullH);if(project&&page===totalPages-1){const approvalY=top+sliceH+8;pdf.setDrawColor(215,222,234);pdf.line(12,approvalY-5,198,approvalY-5);approvalBlock(pdf,project,approvalY)}}pdf.save(name)}
function drawReportHeader(pdf:jsPDF,title:string,p:Project|undefined,page:number,total:number){pdf.setFont('times','bold');pdf.setFontSize(18);pdf.setTextColor(0,0,0);pdf.text(title,12,16);pdf.setFont('times','normal');pdf.setFontSize(10);pdf.setTextColor(0,0,0);if(p)pdf.text(`${p.name}  |  ${p.number||'Project report'}`,12,23);pdf.setDrawColor(65,103,184);pdf.setLineWidth(.7);pdf.line(12,27,198,27);if(p?.logo){try{pdf.addImage(p.logo,'PNG',174,5,24,18)}catch{}}pdf.setFontSize(9);pdf.text(`${page} / ${total}`,198,23,{align:'right'})}
export async function reportPdf(p:Project,data:Record<string,any>,chart:HTMLElement|null,name:string){const [{jsPDF},{default:html2canvas}]=await Promise.all([import('jspdf'),import('html2canvas')]);const pdf=new jsPDF();pdf.setFont('times','bold');pdf.setTextColor(0,0,0);pdf.setFontSize(20);pdf.text('PROJECT ENGINEER - PROJECT REPORT',14,18);pdf.setDrawColor(65,103,184);pdf.setLineWidth(.8);pdf.line(14,23,196,23);pdf.setFont('times','normal');pdf.setTextColor(0,0,0);pdf.setFontSize(10);let y=30;for(const [k,v] of Object.entries(data)){pdf.setFont('times','bold');pdf.setTextColor(0,0,0);pdf.text(`${k}:`,14,y);pdf.setFont('times','normal');pdf.setTextColor(0,0,0);pdf.text(String(v),60,y);y+=7}if(p.logo){try{pdf.addImage(p.logo,'PNG',160,6,35,16)}catch{}}if(chart){const c=await html2canvas(chart,{scale:1.5,backgroundColor:'#fff',useCORS:true});if(y>145){pdf.addPage();y=20}pdf.setFont('times','bold');pdf.setFontSize(13);pdf.setTextColor(0,0,0);pdf.text('PROGRESS OVERVIEW',14,y);pdf.addImage(c.toDataURL('image/png'),'PNG',14,y+5,180,76);y+=88;approvalBlock(pdf,p,y);pdf.save(name);return}approvalBlock(pdf,p,y);pdf.save(name)}
function approvalBlock(pdf:jsPDF,p:Project,y:number){const a=p.approval;if(y>235){pdf.addPage();y=20}pdf.setFont('times','bold');pdf.setTextColor(0,0,0);pdf.setFontSize(13);pdf.text('APPROVAL',14,y);pdf.setFontSize(10);pdf.text('PIHAK PERTAMA',20,y+10);pdf.text('PIHAK KEDUA',115,y+10);if(a.firstSignature)try{pdf.addImage(a.firstSignature,'PNG',20,y+15,45,18)}catch{}if(a.secondSignature)try{pdf.addImage(a.secondSignature,'PNG',115,y+15,45,18)}catch{}pdf.setFont('times','normal');pdf.setTextColor(0,0,0);pdf.setFontSize(10);pdf.text([a.firstCompany,a.firstName,a.firstPosition].filter(Boolean).join('\n'),20,y+40);pdf.text([a.secondCompany,a.secondName,a.secondPosition].filter(Boolean).join('\n'),115,y+40)}
